.TH "CORREIOS" "1" "January 2017" "2.0.0" "correios manual"
.SH "NAME"
\fBcorreios\fR - Busca dados de uma localidade
.SH "SYNOPSIS"
.P
\fBcorreios\fR \[lB]\fBoptions\fR\[rB] <\fIinput\fR>
.SH "DESCRIPTION"
.P
Busca por informações de uma localidade através do endereço ou CEP utilizando os \fBCorreios\fR \fI\(lahttp://www.correios.com.br/\(ra\fR
.SH "OPTIONS"
.SS "\fB-h\fR, \fB--help\fR"
.P
.RS 2
.nf
correios --help
.fi
.RE
.P
Output short usage information.
.SS "\fB-v\fR, \fB--version\fR"
.P
.RS 2
.nf
correios --version
.fi
.RE
.P
Output CLI version number.
.SH "USAGE"
.SS "Por CEP"
.P
.RS 2
.nf
correios 04653055
.fi
.RE
.SS "Por endereço"
.P
.RS 2
.nf
correios "Rua Primo Modolin"
.fi
.RE
.SH "DIAGNOSTICS"
.P
\fBcorreios\fR exits 0 on success, and 1 otherwise.
.SH "BUGS"
.P
\fI\(lahttps://github.com/lagden/io-cep/issues\(ra\fR
.SH "AUTHOR"
.P
Written by Thiago Lagden \fI\(lalagden@gmail.com\(ra\fR
